# Exports
# Android SDK
if [ -d "$HOME/Android/Sdk/" ]; then
  export ANDROID_HOME="$HOME/Android/Sdk"
  export PATH="$PATH:$ANDROID_HOME/build-tools/35.0.1"
fi

EXPORT_PATH() {
  local P="$1"

  if [ -d "$P" ]; then
    export PATH="$PATH:$P"
  fi
}

EXPORT_PATH "$HOME/.local/bin/"
EXPORT_PATH "$HOME/.bin/"
EXPORT_PATH "$XDG_DATA_DIRS:/var/lib/flatpak/exports/share/"
EXPORT_PATH "$HOME/.local/share/flatpak/exports/share/applications/"
EXPORT_PATH "$HOME/.spicetify/"
EXPORT_PATH "$HOME/.scripts/"
EXPORT_PATH "$HOME/.local/lib/"

CMD_CHECK() {
  command -v "$1" &>/dev/null
}

if [ -f "/etc/doas.conf" ] && "CMD_CHECK" "doas"; then
  ROOT="doas"
elif "CMD_CHECK" "sudo"; then
  ROOT="sudo"
else
  echo "WARNING: Doas and sudo not found!"
fi

export QT_QPA_PLATFORM="wayland"

if "CMD_CHECK" "nvim"; then
  export EDITOR="nvim"
  export VISUAL="nvim" 
elif "CMD_CHECK" "vim"; then
  export EDITOR="vim"
  export VISUAL="vim"
elif "CMD_CHECK" "nano"; then
  export EDITOR="nano"
  export VISUAL="nano"
else
  echo "WARNING: neovim, vim and nano not found!"
fi

if "CMD_CHECK" "librewolf"; then
  export BROWSER="/usr/bin/librewolf" 
fi

# Clang
export CLANG_TYPE="aosp"

# Oh My Zsh
plugins=(
  git
  zsh-completions
  zsh-history-substring-search 
  zsh-syntax-highlighting
  )
export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

# Oh My Posh 
POSH=agnoster
eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/EDM115-newline.omp.json)"

# Aliases
# sdcard encrypt
alias mount-sd="mountpoint-sdcrypt; $ROOT cryptsetup open /dev/sda3 sdcard-encrypted; $ROOT mount /dev/mapper/sdcard-encrypted /mnt/sdcard-encrypted"
alias umount-sd="$ROOT umount /mnt/sdcard-encrypted; $ROOT cryptsetup close sdcard-encrypted; "

if grep -q "gentoo" "/etc/os-release"; then
  alias ins="$ROOT emerge -navq"
  alias sup="$ROOT emerge --sync; $ROOT emerge -avq --changed-use --newuse --update --deep @world"
  alias up="$ROOT emerge -avq --changed-use --newuse --update --deep @world"
  alias mc="$ROOT $EDITOR /etc/portage/make.conf" 
elif grep -q "arch" "/etc/os-release"; then
  alias ins="$ROOT pacman -S --needed --noconfirm"
  alias up="$ROOT pacman -Syyuu --needed --noconfirm"
fi

# basic (doas, ls, etc.)
alias l="ls"
alias la="ls -a"
alias s="$ROOT"
alias scp="$ROOT cp -r"
alias catboys="cat"
alias rm="$ROOT rm -rf"
alias v="$EDITOR"
alias d="$ROOT rm -rf"
alias heat="rm"

# Android Dev Stuff
alias sync="repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags"
alias b="make bacon -j$(nproc --all)"

# git
alias gcl="git clone -j$(nproc --all)"
alias gad="git add"
alias gcm="git commit -s -m"
alias gra="git remote add"
alias gpu="git push -u"
alias gin="git init"
alias gbr="git branch"
alias gpl="git pull -j$(nproc --all)"
alias gru="git remote update"
alias gcp="git cherry-pick -s"
alias gccp="git cherry-pick --continue"
alias gst="git status"
alias grm="git remote remove"
alias gck="git checkout"
alias grv="git revert -s"
alias grc="git revert --continue"
alias grs="git revert --skip"
alias grb="git revert --abort"
alias gcs="git cherry-pick --skip"
alias grn="git revert --no-edit -S -s"
alias gco="git commit -s"
alias gca="git commit -s --amend"
alias gmr="git merge -S --signoff --log"
alias gms="git merge --skip"
alias gma="git merge --abort"
alias gre="git restore"
alias grs="git restore --staged"

# zsh
alias zshrc="$EDITOR $HOME/.zshrc"
alias zsh="source $HOME/.zshrc"

# Commands
command_not_found_handler() {
	printf "%s%s?! Learn how to type dumbass fr\n" "$acc" "$0" >&2
  return 127
}

mountpoint-sdcrypt () {
 if [ ! -d "/mnt/sdcard-encrypted" ]; then
    "$ROOT" "mkdir -p /mnt/sdcard-encrypted"
    echo "mountpoint for sdcard-encrypted created"
 fi
}

solvo() {
    for i in {1..100000}; do
        echo "$i solvo explosions please"
    done
}

solvo-vid() {
    timg -V "$HOME/.config/zsh/vids/solvo.webm"
}

# Fastfetch
if "CMD_CHECK" "fastfetch"; then
  fastfetch  
fi

# ccache
if "CMD_CHECK" "ccache"; then
  export USE_CCACHE="1"
  export CCACHE_EXEC="/usr/bin/ccache"
  if [ ! -d "$HOME/.ccache" ]; then
    mkdir -p "$HOME/.ccache/"
    export CCACHE_DIR="/home/ksawlii/.ccache"  
  fi
else
  export USE_CCACHE="0"
fi

# History
setopt auto_cd
setopt correct_all
setopt hist_reduce_blanks
setopt hist_ignore_space
setopt hist_save_no_dups
