# [
check_exec()
{
    command -v "$1" &> /dev/null
    return $?
}

command_not_found_handler()
{
    printf "%s%s?! Learn how to type dumbass fr\n" "$acc" "$0" >&2
    return 127
}

export_path()
{
    for dir in "$@"; do
        [[ -d "$dir" ]] && export PATH="$PATH:$dir"
    done
}

solvo()
{
    for i in {1..100000}; do
        echo "$i solvo explosions please"
    done
}

solvo-vid()
{
    timg -V "$HOME/.config/zsh/vids/solvo.webm"
}
# ]

# Android SDK
if [[ -d "$HOME/Android/Sdk" ]]; then
    export ANDROID_HOME="$HOME/Android/Sdk"
fi

# Exports
export_path \
    "$HOME/.local/bin" \
    "$HOME/.bin" \
    "$HOME/.spicetify" \
    "$HOME/.scripts" \
    "$HOME/.local/lib" \
    "$HOME/.local/share/flatpak/exports/share/applications" \
    "$ANDROID_HOME/build-tools/35.0.1"

export XDG_DATA_DIRS="${XDG_DATA_DIRS:-/usr/share}:/var/lib/flatpak/exports/share"

if [[ -f "/etc/doas.conf" ]] && check_exec "doas"; then
    ROOT="doas"
elif check_exec "sudo"; then
    ROOT="sudo"
else
    echo -e "\033[0;33mWARN: Neither doas nor sudo found!\033[0m"
fi

if check_exec nvim; then
    export EDITOR="nvim"
    export VISUAL="nvim"
elif check_exec vim; then
    export EDITOR="vim"
    export VISUAL="vim"
elif check_exec nano; then
    export EDITOR="nano"
    export VISUAL="nano"
else
    echo -e "\033[0;33mWARN: No editor (nvim, vim, nano) found!\033[0m"
fi

export QT_QPA_PLATFORM="wayland"

# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"
plugins=(
    "git"
    "zsh-completions"
    "zsh-history-substring-search"
    "zsh-syntax-highlighting"
)

source "$ZSH/oh-my-zsh.sh"

# Oh My Posh
eval "$(oh-my-posh init zsh --config "$HOME/.config/ohmyposh/EDM115-newline.omp.json")"

# Aliases
if grep -qi "gentoo" "/etc/os-release"; then
    alias ins="$ROOT emerge -navq"
    alias sup="$ROOT emerge --sync && $ROOT emerge -avq --changed-use --newuse --update --deep @world"
    alias up="$ROOT emerge -avq --changed-use --newuse --update --deep @world"
    alias mc="$ROOT $EDITOR /etc/portage/make.conf"
elif grep -qi "arch" "/etc/os-release"; then
    alias ins="$ROOT pacman -S --needed --noconfirm"
    alias up="$ROOT pacman -Syyuu --needed --noconfirm"
fi

# Basic aliases
alias l="ls"
alias la="ls -a"
alias s="$ROOT"
alias scp="$ROOT cp -r"
alias catboys="cat"
alias rm="$ROOT rm -rf"
alias v="$EDITOR"

# Android
alias sync="repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --jobs-network=8"
alias b="make bacon -j$(nproc --all)"

# Git
alias gcl="git clone -j$(nproc --all)"
alias gad="git add"
alias gcm="git commit -s -m"
alias gra="git remote add"
alias gpu="git push -u"
alias gin="git init"
alias gbr="git branch"
alias gpl="git pull -j$(nproc --all)"
alias gru="git remote update"
alias gcp="git cherry-pick -s"
alias gccp="git cherry-pick --continue"
alias gcs="git cherry-pick --skip"
alias gst="git status"
alias grm="git remote remove"
alias gck="git checkout"
alias grv="git revert -s"
alias grc="git revert --continue"
alias grs="git restore --staged"
alias grb="git revert --abort"
alias grn="git revert --no-edit -S -s"
alias gco="git commit -s"
alias gca="git commit -s --amend"
alias gmr="git merge -S --signoff --log"
alias gms="git merge --skip"
alias gma="git merge --abort"
alias gre="git restore"
alias glo="git --no-pager log --oneline"

# Zsh shortcuts
alias zshrc="$EDITOR $HOME/.zshrc"
alias zsh="source $HOME/.zshrc"

# Fastfetch
check_exec "fastfetch" && fastfetch

# ccache setup
if check_exec "ccache"; then
    export USE_CCACHE=1
    export CCACHE_DIR="$HOME/.ccache"
    [[ -d "$CCACHE_DIR" ]] || mkdir -p "$CCACHE_DIR"
else
    export USE_CCACHE=0
fi

# history
setopt auto_cd
setopt correct_all
setopt hist_reduce_blanks
setopt hist_ignore_space
setopt hist_save_no_dups
