#######################
### INHERIT CONFIGS ###
#######################

source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/look.conf
source = ~/.config/hypr/rules.conf

################
### MONITORS ###
################

## Ksawlii's monitor config (aka disable shitty hp monitor)
# monitor=eDP-1,disable
## Default
# monitor=,preferred,auto,1
monitor=DP-3,1920x1080@240,0x0,1

#################
### AUTOSTART ###
#################

exec-once = swaybg -i "$HOME/.config/hypr/wallpapers/1.png"
exec-once = ~/.config/hypr/xdg-portal-hyprland.sh
exec-once = gentoo-pipewire-launcher &
exec-once = waybar
exec-once = dunst

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland

#############
### INPUT ###
#############

input {
    kb_layout = pl
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    sensitivity = 0
    
    touchpad {
        natural_scroll = false
    }
}

gestures {
    workspace_swipe = false
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
