name: Test install

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  dotfiles:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare system
        run: |
          pacman -Syu --noconfirm sudo
          useradd -m user
          echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R user:user $GITHUB_WORKSPACE
          chown -R user:user /home

      - name: Run install script
        run: |
          su - user -c "cd $GITHUB_WORKSPACE && ./install.sh"
